"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ErrorState, LoadingState, Modal, StatusBadge } from "@/components/ui";
import { entryOperationsApi, masterApi, versionOperationsApi } from "@/lib/api";
import { apiErrorMessage } from "@/lib/api-client";
import { queryKeys } from "@/lib/query-keys";
import type { TimetableEntry } from "@/lib/types";
import { useToast } from "@/providers/toast-provider";

export function EntryActions({ entry, versionId, sectionId, editable, disabledReason, canAudit = true }: { entry: TimetableEntry; versionId: string; sectionId?: string; editable: boolean; disabledReason?: string; canAudit?: boolean }) {
  const [dialog, setDialog] = useState<"move" | "unlock" | "audit" | null>(null);
  const client = useQueryClient(); const { notify } = useToast();
  const invalidate = () => { for (const key of [queryKeys.entries(versionId), queryKeys.conflicts(versionId), queryKeys.version(versionId), queryKeys.audit(entry.id), queryKeys.timetableViews(versionId)]) void client.invalidateQueries({ queryKey: key }); if (sectionId) void client.invalidateQueries({ queryKey: queryKeys.sectionGrid(versionId, sectionId) }); };
  const lock = useMutation({ mutationFn: () => entryOperationsApi.lock(entry.id), onSuccess: () => { notify("Entry locked"); invalidate(); }, onError: (error) => notify(apiErrorMessage(error), "error") });
  const moveDisabledReason = disabledReason ?? (entry.is_locked ? "Unlock this entry before moving it." : undefined);
  return <div className="flex flex-wrap gap-2">{editable && <button className="text-xs font-semibold text-brand-700 disabled:cursor-not-allowed disabled:text-slate-400" title={moveDisabledReason} disabled={Boolean(moveDisabledReason)} onClick={() => setDialog("move")}>Move</button>}{editable && !entry.is_locked && <button className="text-xs font-semibold text-violet-700 disabled:cursor-not-allowed disabled:text-slate-400" title={disabledReason} disabled={lock.isPending || Boolean(disabledReason)} onClick={() => { if (window.confirm("Lock this timetable entry?")) lock.mutate(); }}>Lock</button>}{editable && entry.is_locked && <button className="text-xs font-semibold text-violet-700 disabled:cursor-not-allowed disabled:text-slate-400" title={disabledReason} disabled={Boolean(disabledReason)} onClick={() => setDialog("unlock")}>Unlock</button>}{canAudit && <button className="text-xs font-semibold text-slate-700" onClick={() => setDialog("audit")}>Audit</button>}{dialog === "move" && <MoveDialog entry={entry} versionId={versionId} sectionId={sectionId} onClose={() => setDialog(null)} onChanged={invalidate} />}{dialog === "unlock" && <UnlockDialog entry={entry} onClose={() => setDialog(null)} onChanged={invalidate} />}{dialog === "audit" && <AuditDialog entryId={entry.id} onClose={() => setDialog(null)} />}</div>;
}

export function MoveDialog(props: { entry: TimetableEntry; versionId: string; sectionId?: string; onClose(): void; onChanged(): void }) {
  const { entry, onClose, onChanged } = props;
  const { notify } = useToast(); const [day, setDay] = useState(entry.working_day_id); const [period, setPeriod] = useState(entry.period_number); const [classroom, setClassroom] = useState(entry.classroom_id ?? ""); const [laboratory, setLaboratory] = useState(entry.laboratory_id ?? ""); const [lockAfter, setLockAfter] = useState(true);
  const days = useQuery({ queryKey: queryKeys.workingDays, queryFn: masterApi.workingDays }); const classrooms = useQuery({ queryKey: queryKeys.classrooms("move"), queryFn: () => masterApi.classrooms() }); const laboratories = useQuery({ queryKey: queryKeys.laboratories("move"), queryFn: () => masterApi.laboratories() });
  const solverInput = useQuery({ queryKey: queryKeys.solverInput(props.versionId), queryFn: () => versionOperationsApi.solverInput(props.versionId), retry: false });
  const offering = Array.isArray(solverInput.data?.snapshot_json.course_offerings) ? (solverInput.data.snapshot_json.course_offerings as Record<string, unknown>[]).find((item) => item.id === entry.course_offering_id) : undefined;
  const eligibleLaboratoryIds = new Set(Array.isArray(offering?.eligible_laboratory_ids) ? offering.eligible_laboratory_ids.map(String) : []);
  const eligibleLaboratories = (laboratories.data?.items ?? []).filter((item) => eligibleLaboratoryIds.has(item.id));
  const mutation = useMutation({ mutationFn: () => entryOperationsApi.move(entry.id, { working_day_id: day, period_number: period, classroom_id: classroom || null, laboratory_id: laboratory || null, lock_after_move: lockAfter }), onSuccess: () => { notify("Entry moved successfully"); onChanged(); onClose(); }, onError: () => undefined });
  const currentDay = days.data?.items.find((item) => item.id === entry.working_day_id)?.day_name ?? (days.isLoading ? "Loading working day…" : "Working day unavailable");
  return <Modal title="Move timetable entry" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={!day || mutation.isPending} onClick={() => { if (window.confirm(`Move from period ${entry.period_number} to period ${period}?`)) mutation.mutate(); }}>{mutation.isPending ? "Moving…" : "Move entry"}</button></>}><p className="mb-4 rounded-lg bg-slate-50 p-3 text-sm">Current slot: {currentDay} · Period {entry.period_number} · Session length {entry.session_length}</p><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Target working day</span><select className="field" value={day} onChange={(event) => setDay(event.target.value)}>{days.data?.items.map((item) => <option key={item.id} value={item.id}>{item.day_name}</option>)}</select></label><label><span className="label">Target period</span><select className="field" value={period} onChange={(event) => setPeriod(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7].map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Classroom</span><select className="field" value={classroom} onChange={(event) => setClassroom(event.target.value)}><option value="">No classroom</option>{classrooms.data?.items.map((item) => <option key={item.id} value={item.id}>{[item.room_number, item.room_name].filter(Boolean).join(" · ")}</option>)}</select></label><label><span className="label">Laboratory</span><select className="field" value={laboratory} onChange={(event) => setLaboratory(event.target.value)}><option value="">No laboratory</option>{eligibleLaboratories.map((item) => <option key={item.id} value={item.id}>{[item.laboratory_code, item.laboratory_name].filter(Boolean).join(" · ")}</option>)}</select>{solverInput.isLoading && <span className="mt-1 block text-xs text-slate-500">Loading eligible laboratories…</span>}{solverInput.isError && <span className="mt-1 block text-xs text-amber-700">Eligible laboratory metadata is unavailable; the backend still enforces eligibility.</span>}</label></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={lockAfter} onChange={(event) => setLockAfter(event.target.checked)} />Lock entry after move</label>{mutation.isError && <div className="mt-4"><ErrorState message={apiErrorMessage(mutation.error)} /></div>}</Modal>;
}

export function UnlockDialog({ entry, onClose, onChanged }: { entry: TimetableEntry; onClose(): void; onChanged(): void }) {
  const [reason, setReason] = useState(""); const { notify } = useToast(); const mutation = useMutation({ mutationFn: () => entryOperationsApi.unlock(entry.id, reason.trim()), onSuccess: () => { notify("Entry unlocked"); onChanged(); onClose(); }, onError: () => undefined });
  return <Modal title="Unlock timetable entry" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={!reason.trim() || mutation.isPending} onClick={() => mutation.mutate()}>Unlock entry</button></>}><label><span className="label">Reason</span><textarea className="field min-h-28" value={reason} onChange={(event) => setReason(event.target.value)} /></label>{!reason.trim() && <p className="mt-2 text-xs text-slate-500">A reason is required.</p>}{mutation.isError && <div className="mt-4"><ErrorState message={apiErrorMessage(mutation.error)} /></div>}</Modal>;
}

export function AuditDialog({ entryId, onClose }: { entryId: string; onClose(): void }) {
  const query = useQuery({ queryKey: queryKeys.audit(entryId), queryFn: () => entryOperationsApi.audit(entryId) });
  return <Modal title="Entry audit trail" onClose={onClose} wide>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={apiErrorMessage(query.error)} /> : <ol className="relative ml-3 border-l border-slate-300 pl-6">{query.data!.map((item) => <li key={item.id} className="mb-6"><span className="absolute -left-2 mt-1 h-4 w-4 rounded-full border-2 border-white bg-brand-600" /><div className="flex flex-wrap items-center gap-2"><StatusBadge value={item.action_type} /><time className="text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</time></div><p className="mt-2 text-xs text-slate-500">Performed by {item.performed_by}</p>{item.reason && <p className="mt-2 text-sm">Reason: {item.reason}</p>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><AuditValues title="Old values" values={item.old_values_json} /><AuditValues title="New values" values={item.new_values_json} /></div></li>)}</ol>}</Modal>;
}
function AuditValues({ title, values }: { title: string; values?: Record<string, unknown> | null }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="mb-2 text-xs font-semibold uppercase text-slate-500">{title}</p>{!values ? <span className="text-xs text-slate-400">None</span> : <dl className="space-y-1 text-xs">{Object.entries(values).map(([key, value]) => <div key={key} className="grid grid-cols-2 gap-2"><dt className="text-slate-500">{key.replaceAll("_", " ")}</dt><dd className="break-all font-medium">{String(value ?? "—")}</dd></div>)}</dl>}</div>; }
