"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import type { ResourceDateException } from "@/lib/types";
import { SearchableSelect } from "@/components/searchable-select";
import { Card, EmptyState, ErrorState, LoadingState } from "@/components/ui";
import { api, apiErrorMessage } from "@/lib/api-client";
import { masterDataApi } from "@/lib/master-data-api";
import { readableRecordLabel } from "@/lib/readable-labels";
import { downloadCsv } from "@/lib/csv";
import { parseCsv } from "@/lib/csv-import";
import { resolveResourceAvailabilityCsv, resourceAvailabilityExportRows, resourceAvailabilityTemplate } from "@/lib/resource-availability-csv";
import { RESOURCE_DATE_EXCEPTION_HEADERS, resolveResourceDateExceptionRows, resourceDateExceptionExportRows, resourceDateExceptionTemplate, type ResolvedDateException } from "@/lib/resource-date-exception-csv";
import { getResourceAvailabilityProfile, getResourceAvailabilitySlots } from "@/lib/resource-availability-api";
import { useToast } from "@/providers/toast-provider";

const modes = [["ALL_PERIODS","Available all instructional periods"],["EXCEPT_BLOCKED","Available except blocked periods"],["ONLY_SELECTED","Available only during selected periods"]] as const;
const registry: Record<string,{ endpoint:string; label:string }> = {
  FACULTY:{endpoint:"/faculty",label:"Faculty"}, VISITING_FACULTY:{endpoint:"/faculty",label:"Visiting faculty"},
  CLASSROOM:{endpoint:"/classrooms",label:"Classroom"}, SEMINAR_HALL:{endpoint:"/classrooms",label:"Seminar hall"}, SMART_CLASSROOM:{endpoint:"/classrooms",label:"Smart classroom"}, DRAWING_HALL:{endpoint:"/classrooms",label:"Drawing hall"}, WORKSHOP_ROOM:{endpoint:"/classrooms",label:"Workshop room"}, WORKSHOP:{endpoint:"/classrooms",label:"Workshop"}, GUEST_LECTURE_HALL:{endpoint:"/classrooms",label:"Guest lecture hall"}, GUEST_HALL:{endpoint:"/classrooms",label:"Guest hall"},
  LABORATORY:{endpoint:"/laboratories",label:"Laboratory"},
};
export function ResourceAvailabilityManager({ resourceType, canManage=false, initialResourceId="", initialTermId="", printable=false, occupiedPeriodCount }: { resourceType:string; canManage?:boolean; initialResourceId?:string; initialTermId?:string; printable?:boolean; occupiedPeriodCount?:number }) {
  const kind=resourceType.toUpperCase();const definition=registry[kind] ?? {endpoint:"",label:kind.replaceAll("_"," ")};const client=useQueryClient();const {notify}=useToast();
  const [resourceId,setResourceId]=useState(initialResourceId);const [termId,setTermId]=useState(initialTermId);const[exceptionDate,setExceptionDate]=useState("");const[periodStart,setPeriodStart]=useState("1");const[periodEnd,setPeriodEnd]=useState("7");const[exceptionStatus,setExceptionStatus]=useState("UNAVAILABLE");const[exceptionReason,setExceptionReason]=useState("");const[exceptionPreview,setExceptionPreview]=useState<ResolvedDateException[]>([]);
  const lookups=useQueries({queries:[definition.endpoint,"/academic-terms","/working-days"].map((endpoint)=>({queryKey:["resource-availability-lookup",endpoint],queryFn:()=>masterDataApi.lookup(endpoint,true),enabled:Boolean(endpoint),staleTime:60_000,retry:false}))});
  const resourceData=lookups[0].data;const termData=lookups[1].data;const dayData=lookups[2].data;
  const resources=useMemo(()=>resourceData ?? [],[resourceData]);const terms=useMemo(()=>termData ?? [],[termData]);const days=useMemo(()=>[...(dayData ?? [])].filter((row)=>row.is_active!==false&&row.is_working_day!==false).sort((a,b)=>Number(a.sequence_number)-Number(b.sequence_number)),[dayData]);
  useEffect(()=>{if(initialResourceId)setResourceId(initialResourceId);else if(!resourceId&&resources.length)setResourceId(resources[0].id)},[initialResourceId,resourceId,resources]);
  useEffect(()=>{if(initialTermId)setTermId(initialTermId);else if(!termId&&terms.length)setTermId(terms.find((row)=>row.is_current===true)?.id||terms.find((row)=>row.is_active!==false)?.id||terms[0].id)},[initialTermId,termId,terms]);
  const identifiersReady=Boolean(kind&&resourceId&&termId);
  const profile=useQuery({queryKey:["resource-availability-profile",kind,resourceId,termId],queryFn:()=>getResourceAvailabilityProfile(kind,resourceId,termId),enabled:identifiersReady,retry:false});
  const slots=useQuery({queryKey:["resource-availability-slots",kind,resourceId,termId],queryFn:()=>getResourceAvailabilitySlots(kind,resourceId,termId),enabled:identifiersReady&&profile.data!==null&&profile.data!==undefined,retry:false});
  const exceptions=useQuery({queryKey:["resource-date-exceptions",kind,resourceId,termId],queryFn:async()=>(await api.get<ResourceDateException[]>("/resource-availability/date-exceptions",{params:{resource_type:kind,resource_id:resourceId,academic_term_id:termId}})).data,enabled:identifiersReady,retry:false});
  const resource=resources.find((row)=>row.id===resourceId);const term=terms.find((row)=>row.id===termId);
  const legacyLaboratoryMode=kind==="LABORATORY"
    ? String(resource?.availability_mode??(resource?.is_available_all_periods===false?"EXCEPT_BLOCKED":"ALL_PERIODS"))
    : "ALL_PERIODS";
  const mode=String(profile.data?.availability_mode??legacyLaboratoryMode);
  const slotType=mode==="ONLY_SELECTED"?"ALLOWED":"BLOCKED";const selected=new Map((slots.data??[]).map((row)=>[`${row.working_day_id}:${row.period_number}`,row]));
  const labels=(slots.data??[]).map((row)=>`${String(days.find((day)=>day.id===row.working_day_id)?.day_name??"Day")} P${row.period_number}`).join(", ");const total=days.length*7;const available=mode==="ALL_PERIODS"?total:mode==="EXCEPT_BLOCKED"?Math.max(0,total-selected.size):selected.size;
  const invalidate=()=>Promise.all([client.invalidateQueries({queryKey:["resource-availability-profile",kind,resourceId,termId]}),client.invalidateQueries({queryKey:["resource-availability-slots",kind,resourceId,termId]}),client.invalidateQueries({queryKey:["resource-date-exceptions",kind,resourceId,termId]}),client.invalidateQueries({queryKey:["report"]})]);
  const modeMutation=useMutation({mutationFn:(next:string)=>api.put(`/resource-availability/${kind}/${resourceId}/${termId}`,{availability_mode:next}),onSuccess:()=>{notify(`${definition.label} availability mode updated.`);void invalidate()},onError:(error)=>notify(apiErrorMessage(error),"error")});
  const cellMutation=useMutation({mutationFn:async({dayId,period}:{dayId:string;period:number})=>{const existing=selected.get(`${dayId}:${period}`);if(existing)return api.delete(`/resource-availability/slots/${existing.id}`);return api.post("/resource-availability/slots",{resource_type:kind,resource_id:resourceId,academic_term_id:termId,working_day_id:dayId,period_number:period,availability_type:slotType})},onSuccess:()=>void invalidate(),onError:(error)=>notify(apiErrorMessage(error),"error")});
  const exceptionMutation=useMutation({mutationFn:()=>api.post("/resource-availability/date-exceptions",{resource_type:kind,resource_id:resourceId,academic_term_id:termId,exception_date:exceptionDate,period_start:Number(periodStart),period_end:Number(periodEnd),availability_status:exceptionStatus,reason:exceptionReason||null}),onSuccess:()=>{notify("Date-specific resource exception created.");setExceptionReason("");void invalidate()},onError:(error)=>notify(apiErrorMessage(error),"error")});
  const deleteException=useMutation({mutationFn:(id:string)=>api.delete(`/resource-availability/date-exceptions/${id}`),onSuccess:()=>{notify("Date-specific exception removed.");void invalidate()},onError:(error)=>notify(apiErrorMessage(error),"error")});
  const loading=lookups.some((q)=>q.isLoading)||profile.isLoading||slots.isLoading;const error=lookups.find((q)=>q.error)?.error||profile.error||slots.error;const unconfigured=profile.data===null;
  const importCsv=async(file:File)=>{try{const parsed=parseCsv(await file.text());if(parsed.errors.length)throw new Error(parsed.errors.join(" "));const endpoints=["/faculty","/classrooms","/laboratories","/academic-terms","/working-days"] as const;const rows=await Promise.all(endpoints.map((endpoint)=>masterDataApi.lookup(endpoint,true)));const lookup=Object.fromEntries(endpoints.map((endpoint,index)=>[endpoint,rows[index]]));const resolved=parsed.rows.map((row)=>resolveResourceAvailabilityCsv(row,lookup));const errors=resolved.flatMap((row,index)=>row.errors.map((message)=>`Row ${index+2}: ${message}`));if(errors.length)throw new Error(errors.join(" "));if(!window.confirm(`Import ${resolved.length} validated resource availability record(s)?`))return;for(const row of resolved){await api.put(`/resource-availability/${row.profile!.resource_type}/${row.profile!.resource_id}/${row.profile!.academic_term_id}`,{availability_mode:row.profile!.availability_mode});for(const slot of row.slots)await api.post("/resource-availability/slots",slot)}notify(`${resolved.length} resource availability record(s) imported.`);await invalidate()}catch(importError){notify(apiErrorMessage(importError),"error")}};
  const exportAvailability=()=>{try{if(!resource||!term)throw new Error("Select a resource and academic term before exporting.");downloadCsv(`${kind.toLowerCase()}-availability`,resourceAvailabilityExportRows(kind,resource,term,mode,slots.data??[],days));notify("Resource availability exported.")}catch(exportError){notify(apiErrorMessage(exportError),"error")}};
  const importDateExceptions=async(file:File)=>{try{if(!resource||!term)throw new Error("Select a resource and Academic Term before importing.");const parsed=parseCsv(await file.text());if(parsed.errors.length)throw new Error(parsed.errors.join(" "));const missing=RESOURCE_DATE_EXCEPTION_HEADERS.filter((header)=>!parsed.headers.includes(header));if(missing.length)throw new Error(`Missing CSV column(s): ${missing.join(", ")}`);setExceptionPreview(resolveResourceDateExceptionRows(parsed.rows,kind,resource,term,exceptions.data??[]))}catch(importError){notify(apiErrorMessage(importError),"error")}};
  const applyDateExceptions=async()=>{try{if(exceptionPreview.some((row)=>row.status==="INVALID"||row.status==="CONFLICT"))throw new Error("Resolve invalid or conflicting rows before import.");const changed=exceptionPreview.filter((row)=>row.status==="CHANGED");if(changed.length&&!window.confirm(`Replace ${changed.length} changed date exception(s)?`))return;let inserted=0,updated=0,skipped=0;for(const row of exceptionPreview){if(row.status==="IDENTICAL"){skipped+=1;continue}if(!row.payload)continue;if(row.status==="CHANGED"&&row.existing){await api.delete(`/resource-availability/date-exceptions/${row.existing.id}`);updated+=1}else inserted+=1;await api.post("/resource-availability/date-exceptions",row.payload)}notify(`${inserted} inserted, ${updated} updated, ${skipped} skipped.`);setExceptionPreview([]);await invalidate()}catch(importError){notify(apiErrorMessage(importError),"error")}};
  const exportDateExceptions=()=>{if(!resource||!term)return;downloadCsv(`${kind.toLowerCase()}-date-exceptions`,resourceDateExceptionExportRows(kind,resource,term,exceptions.data??[]));notify("Date-specific exceptions exported.")};
  return <Card title={`${definition.label} weekly availability`} className="mt-5">
    {!printable&&<div className="mb-4 grid gap-3 md:grid-cols-2"><SearchableSelect label={definition.label} value={resourceId} options={resources.map((row)=>({value:row.id,label:readableRecordLabel(definition.endpoint,row)}))} onChange={setResourceId} loading={lookups[0].isLoading} emptyMessage={`No ${definition.label.toLowerCase()} records available`} /><SearchableSelect label="Academic term" value={termId} options={terms.map((row)=>({value:row.id,label:readableRecordLabel("/academic-terms",row)}))} onChange={setTermId} loading={lookups[1].isLoading} emptyMessage="No academic terms available" /></div>}
    {!printable&&canManage&&<div className="mb-4 flex flex-wrap gap-2"><button className="button-secondary" onClick={()=>downloadCsv("resource-availability-template",resourceAvailabilityTemplate(kind))}>Download business-key CSV template</button><button className="button-secondary" disabled={!resource||!term||profile.isLoading||slots.isLoading} onClick={exportAvailability}>Export availability CSV</button><label className="button-secondary cursor-pointer">Import availability CSV<input className="sr-only" type="file" accept=".csv,text/csv" onChange={(event)=>{const file=event.target.files?.[0];if(file)void importCsv(file);event.target.value=""}}/></label></div>}
    {loading?<LoadingState/>:error?<ErrorState message={apiErrorMessage(error)} retry={()=>{void Promise.all([profile.refetch(),profile.data?slots.refetch():Promise.resolve(),...lookups.map((query)=>query.refetch())])}}/>:!resource?<EmptyState title={`Select a ${definition.label.toLowerCase()}`}/>:!termId?<EmptyState title="Select an academic term"/>:<>
      {unconfigured&&<div className="mb-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-100"><div><p className="font-semibold">Availability not configured</p><p>{mode==="ALL_PERIODS"?"Available all instructional periods (default)":`${modes.find(([value])=>value===mode)?.[1]??mode} (legacy default)`}</p></div>{canManage&&!printable&&<button className="button-primary" disabled={modeMutation.isPending||!termId} onClick={()=>modeMutation.mutate(mode)}>{modeMutation.isPending?"Configuring…":"Configure Availability"}</button>}</div>}
      {!unconfigured&&<fieldset className="mb-4 print:hidden"><legend className="label">Availability Mode</legend><div className="grid gap-2 sm:grid-cols-3">{modes.map(([value,label])=><label key={value} className="flex items-center gap-2 rounded-lg border p-3 text-sm dark:border-slate-700"><input type="radio" name={`${kind}_availability_mode`} value={value} checked={mode===value} disabled={!canManage||modeMutation.isPending||!termId} onChange={()=>modeMutation.mutate(value)}/>{label}</label>)}</div></fieldset>}
      <dl className="mb-4 grid gap-2 rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Availability Mode" value={modes.find(([value])=>value===mode)?.[1]??mode}/><Metric label="Blocked Periods" value={mode==="EXCEPT_BLOCKED"?labels||"None":"Not applicable"}/><Metric label="Allowed Periods" value={mode==="ONLY_SELECTED"?labels||"None":mode==="ALL_PERIODS"?"All instructional periods":"All except blocked"}/>{occupiedPeriodCount!==undefined&&<Metric label="Utilization of available periods" value={`${occupiedPeriodCount} / ${available} (${available?Math.round(occupiedPeriodCount/available*100):0}%)`}/>}</dl>
      <div className="mb-3 flex flex-wrap gap-3 text-xs"><Legend color="bg-emerald-100" label="Available"/><Legend color="bg-red-100" label="Blocked"/><Legend color="bg-slate-200" label="Unavailable"/></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-center text-sm"><thead><tr><th className="p-2 text-left">Day</th>{[1,2,3,4,5,6,7].map((period)=><th key={period} className="p-2">P{period}</th>)}</tr></thead><tbody>{days.map((day)=><tr key={day.id}><th className="border p-2 text-left dark:border-slate-700">{String(day.day_name)}</th>{[1,2,3,4,5,6,7].map((period)=>{const marked=selected.has(`${day.id}:${period}`);const state=mode==="ALL_PERIODS"?"Available":mode==="EXCEPT_BLOCKED"?(marked?"Blocked":"Available"):(marked?"Available":"Unavailable");const color=state==="Available"?"bg-emerald-100 text-emerald-900 dark:bg-emerald-950/50":state==="Blocked"?"bg-red-100 text-red-900 dark:bg-red-950/50":"bg-slate-200 text-slate-600 dark:bg-slate-800";return <td key={period} className={`border p-1 dark:border-slate-700 ${color}`}><button aria-label={`${String(day.day_name)} P${period}: ${state}`} className="h-10 w-full disabled:cursor-default" disabled={!canManage||mode==="ALL_PERIODS"||cellMutation.isPending} onClick={()=>cellMutation.mutate({dayId:day.id,period})}>{state}</button></td>})}</tr>)}</tbody></table></div>
      <p className="mt-3 text-xs text-slate-500">{mode==="ALL_PERIODS"?"Every instructional period is available; no slot configuration is needed.":mode==="EXCEPT_BLOCKED"?"Selected cells are hard blocked periods.":"Only selected cells are permitted for scheduling."}</p>
      {!printable&&canManage&&<div className="mt-5 rounded-lg border p-3 dark:border-slate-700"><h3 className="mb-2 font-semibold">Date exception CSV</h3><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={()=>downloadCsv("resource-date-exceptions-template",resourceDateExceptionTemplate(kind))}>Download exception CSV template</button><button className="button-secondary" disabled={!resource||!term||exceptions.isLoading} onClick={exportDateExceptions}>Export exception CSV</button><label className="button-secondary cursor-pointer">Import exception CSV<input className="sr-only" type="file" accept=".csv,text/csv" onChange={(event)=>{const file=event.target.files?.[0];if(file)void importDateExceptions(file);event.target.value=""}}/></label></div>{exceptionPreview.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Row","Readable resource","Date / periods","Status","Message"].map((label)=><th className="px-2 py-1 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{exceptionPreview.map((row)=><tr key={row.rowNumber}><td className="px-2 py-1">{row.rowNumber}</td><td className="px-2 py-1">{row.source.resource_code} · {row.source.academic_term_code}</td><td className="px-2 py-1">{row.source.exception_date} · {row.source.period_start&&row.source.period_end?`P${row.source.period_start}–P${row.source.period_end}`:"All day"}</td><td className="px-2 py-1 font-semibold">{row.status}</td><td className="px-2 py-1">{row.message}</td></tr>)}</tbody></table><div className="mt-2 flex gap-2"><button className="button-primary" onClick={()=>void applyDateExceptions()}>Apply NEW / CHANGED rows</button><button className="button-secondary" onClick={()=>setExceptionPreview([])}>Keep Existing / Cancel</button></div></div>}</div>}
      {!printable&&<div className="mt-5 border-t pt-4 dark:border-slate-700"><h3 className="font-semibold">Date-specific exceptions</h3><p className="mb-3 text-xs text-slate-500">A one-off exception overrides the recurring weekly availability on its date.</p>{canManage&&<div className="grid gap-2 md:grid-cols-6"><label><span className="label">Date</span><input aria-label="Exception date" className="field" type="date" value={exceptionDate} onChange={(event)=>setExceptionDate(event.target.value)}/></label><label><span className="label">From period</span><select aria-label="Exception start period" className="field" value={periodStart} onChange={(event)=>setPeriodStart(event.target.value)}>{[1,2,3,4,5,6,7].map((period)=><option key={period}>{period}</option>)}</select></label><label><span className="label">To period</span><select aria-label="Exception end period" className="field" value={periodEnd} onChange={(event)=>setPeriodEnd(event.target.value)}>{[1,2,3,4,5,6,7].map((period)=><option key={period}>{period}</option>)}</select></label><label><span className="label">Override</span><select aria-label="Exception availability" className="field" value={exceptionStatus} onChange={(event)=>setExceptionStatus(event.target.value)}><option value="UNAVAILABLE">Unavailable</option><option value="AVAILABLE">Available</option></select></label><label><span className="label">Reason</span><input aria-label="Exception reason" className="field" value={exceptionReason} onChange={(event)=>setExceptionReason(event.target.value)}/></label><button className="button-primary self-end" disabled={!exceptionDate||Number(periodEnd)<Number(periodStart)||exceptionMutation.isPending} onClick={()=>exceptionMutation.mutate()}>{exceptionMutation.isPending?"Adding…":"Add exception"}</button></div>}<div className="mt-3 flex flex-wrap gap-2">{exceptions.isLoading?<span className="text-sm">Loading exceptions…</span>:exceptions.data?.length?exceptions.data.map((item)=><span className={`rounded-full px-3 py-1 text-xs ${item.availability_status==="UNAVAILABLE"?"bg-red-100 text-red-800":"bg-emerald-100 text-emerald-800"}`} key={item.id}>{item.exception_date} · P{item.period_start}–P{item.period_end} · {item.availability_status}{canManage&&<button aria-label={`Remove exception ${item.exception_date}`} className="ml-2 font-bold" disabled={deleteException.isPending} onClick={()=>deleteException.mutate(item.id)}>×</button>}</span>):<span className="text-sm text-slate-500">No one-off exceptions configured.</span>}</div></div>}
    </>}
  </Card>;
}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="font-semibold">{value}</dd></div>}
function Legend({color,label}:{color:string;label:string}){return <span className="inline-flex items-center gap-1"><span className={`h-3 w-3 rounded ${color}`}/>{label}</span>}
