"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FileUp, RefreshCw, Shuffle } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { SearchableSelect } from "@/components/searchable-select";
import { Card, EmptyState, ErrorState, LoadingState, Modal } from "@/components/ui";
import { apiErrorMessage } from "@/lib/api-client";
import { masterDataApi, type MasterRecord, type RotationAssignment, type RotationMatrix } from "@/lib/master-data-api";
import { readableRecordLabel } from "@/lib/readable-labels";
import { downloadCsv } from "@/lib/csv";
import { parseCsv } from "@/lib/csv-import";
import { resolveRotationCsvRow, rotationAssignmentCsvColumns } from "@/lib/rotation-csv";
import { useToast } from "@/providers/toast-provider";

const endpoints = ["/sections", "/academic-terms", "/course-offerings", "/courses", "/laboratory-batch-configurations", "/student-batches", "/laboratories", "/faculty"] as const;

export function RotationMatrixManager({ rotations, canManage }: { rotations: MasterRecord[]; canManage: boolean }) {
  const client = useQueryClient(); const { notify } = useToast();
  const [rotationId, setRotationId] = useState(""); const [generating, setGenerating] = useState(false); const [importing, setImporting] = useState(false); const [editing, setEditing] = useState<RotationAssignment | null>(null);
  useEffect(() => { if (!rotations.some((row) => row.id === rotationId)) setRotationId(rotations[0]?.id ?? ""); }, [rotations, rotationId]);
  const lookups = useQueries({ queries: endpoints.map((endpoint) => ({ queryKey: ["rotation-matrix-lookup", endpoint], queryFn: () => masterDataApi.lookup(endpoint), staleTime: 60_000, retry: false })) });
  const records = Object.fromEntries(endpoints.map((endpoint, index) => [endpoint, lookups[index].data ?? []])) as Record<string, MasterRecord[]>;
  const matrix = useQuery({ queryKey: ["rotation-matrix", rotationId], queryFn: () => masterDataApi.rotationMatrix(rotationId), enabled: Boolean(rotationId), retry: false });
  const labels = useMemo(() => Object.fromEntries(Object.entries(records).map(([endpoint, rows]) => [endpoint, new Map(rows.map((row) => [row.id, readableRecordLabel(endpoint, row)]))])), [records]);
  const conflicts = useMemo(() => (matrix.data?.blocks ?? []).flatMap((block) => {
    const duplicate = (values: (string | undefined | null)[]) => values.filter(Boolean).length !== new Set(values.filter(Boolean)).size;
    const rows = block.assignments; const messages: string[] = [];
    if (duplicate(rows.map((row) => row.batch_id))) messages.push("Student group duplicated");
    if (duplicate(rows.map((row) => row.course_offering_id)) || duplicate(rows.map((row) => row.laboratory_id))) messages.push("Laboratory duplicated");
    if (duplicate(rows.flatMap((row) => [row.main_faculty_id, ...(row.supporting_faculty_ids ?? [])]))) messages.push("Faculty duplicated");
    if (new Set(rows.map((row) => row.session_duration)).size > 1) messages.push("Duration mismatch");
    return messages.map((message) => `Block ${block.block_number}: ${message}`);
  }), [matrix.data]);
  const refresh = () => client.invalidateQueries({ queryKey: ["rotation-matrix", rotationId] });
  return <Card title="Synchronized laboratory rotation" className="mt-5">
    <div className="mb-4 flex flex-wrap items-end gap-3">
      <div className="min-w-72 flex-1"><SearchableSelect label="Rotation group" value={rotationId} options={rotations.map((row) => ({ value: row.id, label: String(row.rotation_code), description: [labels["/sections"]?.get(String(row.section_id)), row.rotation_type].filter(Boolean).join(" · ") }))} onChange={setRotationId} emptyMessage="No rotation groups" /></div>
      <button className="button-secondary gap-2" disabled={!rotationId || matrix.isFetching} onClick={() => void matrix.refetch()}><RefreshCw className={`h-4 w-4 ${matrix.isFetching ? "animate-spin" : ""}`} />Refresh matrix</button>
      <button className="button-secondary gap-2" onClick={() => downloadCsv("laboratory-rotation-assignments-template", [Object.fromEntries(rotationAssignmentCsvColumns.map((column) => [column, ""]))])}><Download className="h-4 w-4" />CSV template</button>
      {canManage && matrix.data && <button className="button-secondary gap-2" onClick={() => setImporting(true)}><FileUp className="h-4 w-4" />Import matrix CSV</button>}
      {canManage && <button className="button-primary gap-2" onClick={() => setGenerating(true)}><Shuffle className="h-4 w-4" />Generate rotation</button>}
    </div>
    {lookups.some((query) => query.isError) && <p role="status" className="mb-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Some readable selector metadata could not be loaded.</p>}
    {!rotationId ? <EmptyState title="No rotation selected" detail="Generate a cyclic matrix or choose an existing rotation group." /> : matrix.isLoading ? <LoadingState /> : matrix.isError ? <ErrorState message={apiErrorMessage(matrix.error)} retry={() => void matrix.refetch()} /> : !matrix.data?.blocks.length ? <EmptyState title="Rotation matrix is empty" detail="Generate blocks or add assignments to this group." /> : <>
      <div className="mb-4 grid gap-3 sm:grid-cols-3"><Summary label="Student groups" value={matrix.data.student_group_ids.length} /><Summary label="Laboratory offerings" value={matrix.data.course_offering_ids.length} /><Summary label="Weekly synchronized blocks" value={matrix.data.blocks.length} /></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] border-collapse text-sm"><thead><tr><th className="border bg-slate-50 p-3 text-left dark:border-slate-700 dark:bg-slate-800">Rotation block</th>{matrix.data.student_group_ids.map((id) => <th key={id} className="border bg-slate-50 p-3 text-left dark:border-slate-700 dark:bg-slate-800">{labels["/student-batches"]?.get(id) ?? "Student group"}</th>)}</tr></thead><tbody>{matrix.data.blocks.map((block) => <tr key={block.id}><th className="border p-3 text-left align-top dark:border-slate-700">{block.block_name || `Block ${block.block_number}`}<div className="mt-1 text-xs font-normal text-slate-500">Scheduled as one unit</div></th>{matrix.data!.student_group_ids.map((batchId) => { const assignment = block.assignments.find((row) => row.batch_id === batchId); return <td key={batchId} className="border p-2 align-top dark:border-slate-700">{assignment ? <button type="button" disabled={!canManage} onClick={() => setEditing(assignment)} className="w-full rounded-lg bg-cyan-50 p-3 text-left hover:bg-cyan-100 disabled:cursor-default dark:bg-cyan-950/30"><strong>{labels["/course-offerings"]?.get(assignment.course_offering_id) ?? "Offering metadata unavailable"}</strong><span className="mt-1 block text-xs">{assignment.laboratory_id ? labels["/laboratories"]?.get(assignment.laboratory_id) ?? "Laboratory metadata unavailable" : "Automatic eligible laboratory"}</span><span className="block text-xs">{labels["/faculty"]?.get(assignment.main_faculty_id) ?? "Faculty metadata unavailable"}</span><span className="block text-xs text-slate-500">{assignment.session_duration} periods</span></button> : <span className="text-red-700">Missing assignment</span>}</td>; })}</tr>)}</tbody></table></div>
      <div className={`mt-4 rounded-lg p-3 text-sm ${conflicts.length ? "bg-red-50 text-red-800 dark:bg-red-950/30" : "bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30"}`}><strong>Conflict preview:</strong> {conflicts.length ? conflicts.join("; ") : "No duplicate group, room, faculty, or duration conflicts detected."}</div>
    </>}
    {generating && <GenerateRotation records={records} onClose={() => setGenerating(false)} onComplete={(id) => { setGenerating(false); setRotationId(id); void client.invalidateQueries({ queryKey: ["master-data", "rotations"] }); void client.invalidateQueries({ queryKey: ["rotation-matrix", id] }); }} />}
    {importing && matrix.data && <RotationCsvImport matrix={matrix.data} records={records} onClose={() => setImporting(false)} onComplete={() => { setImporting(false); void refresh(); }} />}
    {editing && <AssignmentEditor assignment={editing} records={records} labels={labels} onClose={() => setEditing(null)} onComplete={() => { setEditing(null); void refresh(); notify("Rotation assignment updated."); }} />}
  </Card>;
}

function RotationCsvImport({ matrix, records, onClose, onComplete }: { matrix: RotationMatrix; records: Record<string, MasterRecord[]>; onClose(): void; onComplete(): void }) {
  const { notify } = useToast(); const [rows, setRows] = useState<ReturnType<typeof resolveRotationCsvRow>[]>([]); const [busy, setBusy] = useState(false);
  const valid = rows.filter((row) => !row.errors.length && row.payload);
  const run = async () => { setBusy(true); try { const blockIds = new Map(matrix.blocks.map((block) => [block.block_number, block.id])); for (const row of valid) { let blockId = blockIds.get(row.blockNumber!); if (!blockId) { const created = await masterDataApi.createRotationBlock(matrix.group.id, { block_number: row.blockNumber!, block_name: `Block ${row.blockNumber}` }); blockId = created.id; blockIds.set(row.blockNumber!, blockId); } const payload = { ...row.payload, rotation_block_id: blockId }; if (row.assignmentId) await masterDataApi.updateRotationAssignment(row.assignmentId, payload); else await masterDataApi.createRotationAssignment(matrix.group.id, payload); } notify(`${valid.length} rotation assignments imported.`); onComplete(); } catch (error) { notify(apiErrorMessage(error), "error"); } finally { setBusy(false); } };
  return <Modal title="Import rotation matrix CSV" onClose={onClose} wide><div className="space-y-4"><p className="text-sm">Use section, academic-term, course, laboratory, faculty, and student-group business keys. UUIDs are resolved internally.</p><input aria-label="Rotation CSV file" type="file" accept=".csv,text/csv" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; void file.text().then((text) => { const parsed = parseCsv(text); setRows(parsed.rows.map((row) => resolveRotationCsvRow(row, matrix, records))); }); }} />{rows.length > 0 && <div className="max-h-80 overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Original business keys</th><th className="p-2">Resolved records</th><th className="p-2">Status</th></tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td className="border-t p-2">{Object.values(row.source).filter(Boolean).join(" · ")}</td><td className="border-t p-2">{row.resolved.join("; ")}</td><td className={`border-t p-2 ${row.errors.length ? "text-red-700" : "text-emerald-700"}`}>{row.errors.join("; ") || (row.assignmentId ? "Ready to update" : "Ready to insert")}</td></tr>)}</tbody></table></div>}<div className="flex justify-end gap-2"><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={!valid.length || busy} onClick={() => void run()}>{busy ? "Importing…" : `Import ${valid.length} assignments`}</button></div></div></Modal>;
}

function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><div className="text-xs text-slate-500">{label}</div><div className="text-xl font-bold">{value}</div></div>; }

function GenerateRotation({ records, onClose, onComplete }: { records: Record<string, MasterRecord[]>; onClose(): void; onComplete(id: string): void }) {
  const { notify } = useToast(); const [sectionId, setSectionId] = useState(""); const [termId, setTermId] = useState(""); const [code, setCode] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [filter, setFilter] = useState("");
  const configurations = new Map(records["/laboratory-batch-configurations"].map((row) => [String(row.course_offering_id), Number(row.number_of_groups)]));
  const offerings = records["/course-offerings"].filter((row) => row.section_id === sectionId && row.academic_term_id === termId && (configurations.get(row.id) ?? 0) > 1 && readableRecordLabel("/course-offerings", row).toLowerCase().includes(filter.toLowerCase()));
  const independent = records["/course-offerings"].filter((row) => row.section_id === sectionId && row.academic_term_id === termId && configurations.get(row.id) === 1);
  const mutation = useMutation({ mutationFn: () => masterDataApi.generateRotation({ section_id: sectionId, academic_term_id: termId, rotation_code: code, course_offering_ids: selected }), onSuccess: (result) => { notify("Synchronized rotation generated."); onComplete(result.group.id); }, onError: (error) => notify(apiErrorMessage(error), "error") });
  return <Modal title="Generate cyclic rotation" onClose={onClose}><div className="space-y-4"><SearchableSelect label="Section" value={sectionId} options={records["/sections"].map((row) => ({ value: row.id, label: readableRecordLabel("/sections", row) }))} onChange={(value) => { setSectionId(value); setSelected([]); }} /><SearchableSelect label="Academic term" value={termId} options={records["/academic-terms"].map((row) => ({ value: row.id, label: readableRecordLabel("/academic-terms", row) }))} onChange={(value) => { setTermId(value); setSelected([]); }} /><label><span className="label">Rotation code</span><input className="field" value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="CSE-A-LABS" /></label><label><span className="label">Search compatible laboratory offerings</span><input className="field" value={filter} onChange={(event) => setFilter(event.target.value)} /></label><fieldset className="max-h-64 space-y-2 overflow-y-auto rounded-lg border p-3 dark:border-slate-700"><legend className="px-1 text-sm font-semibold">Rotation laboratories (more than one group)</legend>{offerings.length ? offerings.map((row) => <label key={row.id} className="flex gap-2"><input type="checkbox" checked={selected.includes(row.id)} onChange={() => setSelected((current) => current.includes(row.id) ? current.filter((id) => id !== row.id) : [...current, row.id])} /><span>{readableRecordLabel("/course-offerings", row)} <small className="text-slate-500">({configurations.get(row.id)} groups)</small></span></label>) : <p className="text-sm text-slate-500">No compatible multi-group laboratories.</p>}</fieldset>{independent.length > 0 && <div className="rounded-lg bg-slate-50 p-3 text-sm dark:bg-slate-800"><strong>Independent full-section laboratories:</strong> {independent.map((row) => readableRecordLabel("/course-offerings", row)).join(", ")}. These remain outside the rotation.</div>}<div className="flex justify-end gap-2"><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={!sectionId || !termId || !code || selected.length < 2 || mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Generating…" : "Generate matrix"}</button></div></div></Modal>;
}

function AssignmentEditor({ assignment, records, labels, onClose, onComplete }: { assignment: RotationAssignment; records: Record<string, MasterRecord[]>; labels: Record<string, Map<string, string>>; onClose(): void; onComplete(): void }) {
  const { notify } = useToast(); const [supportSearch, setSupportSearch] = useState(""); const [values, setValues] = useState({ course_offering_id: assignment.course_offering_id, batch_id: assignment.batch_id, laboratory_id: assignment.laboratory_id ?? "", main_faculty_id: assignment.main_faculty_id, supporting_faculty_ids: assignment.supporting_faculty_ids ?? [], session_duration: assignment.session_duration });
  const options = (endpoint: string) => [
    ...(endpoint === "/laboratories" ? [{ value: "", label: "Automatic eligible laboratory" }] : []),
    ...records[endpoint].map((row) => ({ value: row.id, label: labels[endpoint]?.get(row.id) ?? readableRecordLabel(endpoint, row) })),
  ];
  const mutation = useMutation({ mutationFn: () => masterDataApi.updateRotationAssignment(assignment.id, { ...values, laboratory_id: values.laboratory_id || null }), onSuccess: onComplete, onError: (error) => notify(apiErrorMessage(error), "error") });
  const supportingOptions = options("/faculty").filter((option) => option.value !== values.main_faculty_id && option.label.toLowerCase().includes(supportSearch.toLowerCase()));
  return <Modal title="Edit synchronized assignment" onClose={onClose}><div className="space-y-4"><SearchableSelect label="Student group" value={values.batch_id} options={options("/student-batches")} onChange={(value) => setValues((current) => ({ ...current, batch_id: value }))} /><SearchableSelect label="Laboratory course" value={values.course_offering_id} options={options("/course-offerings")} onChange={(value) => setValues((current) => ({ ...current, course_offering_id: value }))} /><SearchableSelect label="Laboratory room" value={values.laboratory_id} options={options("/laboratories")} onChange={(value) => setValues((current) => ({ ...current, laboratory_id: value }))} /><SearchableSelect label="Main faculty" value={values.main_faculty_id} options={options("/faculty")} onChange={(value) => setValues((current) => ({ ...current, main_faculty_id: value }))} /><fieldset className="rounded-lg border p-3 dark:border-slate-700"><legend className="px-1 text-sm font-semibold">Supporting faculty</legend><input className="field mb-2" aria-label="Search supporting faculty" placeholder="Search by faculty code or name" value={supportSearch} onChange={(event) => setSupportSearch(event.target.value)} /><div className="max-h-32 space-y-1 overflow-y-auto">{supportingOptions.map((option) => <label key={option.value} className="flex gap-2 text-sm"><input type="checkbox" checked={values.supporting_faculty_ids.includes(option.value)} onChange={() => setValues((current) => ({ ...current, supporting_faculty_ids: current.supporting_faculty_ids.includes(option.value) ? current.supporting_faculty_ids.filter((id) => id !== option.value) : [...current.supporting_faculty_ids, option.value] }))} />{option.label}</label>)}</div></fieldset><label><span className="label">Session duration</span><select className="field" value={values.session_duration} onChange={(event) => setValues((current) => ({ ...current, session_duration: Number(event.target.value) }))}><option value={2}>2 periods</option><option value={3}>3 periods</option></select></label><div className="flex justify-end gap-2"><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={mutation.isPending} onClick={() => mutation.mutate()}>{mutation.isPending ? "Saving…" : "Save assignment"}</button></div></div></Modal>;
}
