"use client";

import { Check, ChevronDown, Search } from "lucide-react";
import { useEffect, useId, useMemo, useRef, useState } from "react";

export type SelectOption = { value: string; label: string; description?: string };

export function SearchableSelect({ label, value, options, onChange, loading = false, error, disabled = false, placeholder = "Search and select…", emptyMessage = "No options available" }: { label: string; value: string; options: SelectOption[]; onChange(value: string): void; loading?: boolean; error?: string; disabled?: boolean; placeholder?: string; emptyMessage?: string }) {
  const listId = useId(); const wrapper = useRef<HTMLDivElement>(null); const selected = options.find((option) => option.value === value);
  const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  useEffect(() => { if (!open) setQuery(selected?.label ?? ""); }, [open, selected?.label]);
  useEffect(() => { const outside = (event: MouseEvent) => { if (!wrapper.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", outside); return () => document.removeEventListener("mousedown", outside); }, []);
  const filtered = useMemo(() => options.filter((option) => `${option.label} ${option.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [options, query]);
  const choose = (option: SelectOption) => { onChange(option.value); setQuery(option.label); setOpen(false); };
  return <div ref={wrapper} className="relative"><label><span className="label">{label}</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input role="combobox" aria-label={label} aria-expanded={open} aria-controls={listId} aria-autocomplete="list" className="field pl-9 pr-9" disabled={disabled || loading} placeholder={loading ? `Loading ${label.toLowerCase()}…` : placeholder} value={open ? query : selected?.label ?? ""} onFocus={() => { setOpen(true); setQuery(""); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} onKeyDown={(event) => { if (event.key === "Escape") setOpen(false); if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); } if (event.key === "Enter" && open && filtered[0]) { event.preventDefault(); choose(filtered[0]); } }} /><button type="button" tabIndex={-1} aria-label={`Toggle ${label}`} disabled={disabled || loading} className="absolute right-1 top-1 rounded p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={() => setOpen((current) => !current)}><ChevronDown className="h-4 w-4" /></button></div></label>{error && <p role="alert" className="mt-1 text-xs text-red-700">{error}</p>}{open && !disabled && !loading && <div id={listId} role="listbox" aria-label={`${label} options`} className="absolute z-40 mt-1 max-h-64 w-full overflow-y-auto rounded-lg border border-slate-200 bg-white p-1 shadow-xl dark:border-slate-700 dark:bg-slate-900">{!filtered.length ? <p className="px-3 py-4 text-sm text-slate-500">{emptyMessage}</p> : filtered.map((option) => <button type="button" role="option" aria-selected={option.value === value} key={option.value} className="flex w-full items-start gap-2 rounded-md px-3 py-2 text-left hover:bg-brand-50 dark:hover:bg-slate-800" onMouseDown={(event) => event.preventDefault()} onClick={() => choose(option)}><Check className={`mt-0.5 h-4 w-4 shrink-0 ${option.value === value ? "text-brand-700" : "invisible"}`} /><span><span className="block text-sm font-medium">{option.label}</span>{option.description && <span className="block text-xs text-slate-500">{option.description}</span>}</span></button>)}</div>}</div>;
}
