import { render,screen,within } from "@testing-library/react";
import { describe,expect,it } from "vitest";
import { SectionTimetableGrid } from "@/components/section-timetable-grid";
import type { TimetableGrid } from "@/lib/types";

describe("SectionTimetableGrid",()=>{
  it("renders a two-period laboratory using a two-column span",()=>{const grid:TimetableGrid={version_id:"v",view_type:"section",resource_id:"s",schedule_type:"FIRST_YEAR",days:[{working_day_id:"m",day_name:"Monday",sequence_number:1,entries:[{entry_id:"e",working_day_id:"m",day_name:"Monday",period_number:3,period_numbers:[3,4],schedule_type:"FIRST_YEAR",start_time:"11:00:00",end_time:"12:40:00",course_code:"CS101L",course_name:"Programming Laboratory",course_type:"LABORATORY",section_code:"CSE-A",faculty_code:"VCE001",classroom_room_number:null,laboratory_code:"LAB-1",laboratory_name:"Programming Lab",batch_name:"A1",session_length:2,entry_status:"LOCKED",is_manual:false,is_locked:true}]}]};render(<SectionTimetableGrid grid={grid}/>);const cell=screen.getByText("CS101L").closest("td");expect(cell).toHaveAttribute("colspan","2");expect(within(cell!).getByText("LOCKED")).toBeInTheDocument();expect(screen.getByText("Programming Laboratory")).toBeInTheDocument()});
  it("renders parallel rotation children inside one synchronized block cell",()=>{const common={working_day_id:"m",day_name:"Monday",period_number:1,period_numbers:[1,2],schedule_type:"FIRST_YEAR",start_time:"09:10:00",end_time:"11:00:00",course_type:"LABORATORY",section_code:"CSE-A",session_length:2,entry_status:"GENERATED",is_manual:false,is_locked:false,laboratory_rotation_block_id:"block-1"};const grid:TimetableGrid={version_id:"v",view_type:"section",resource_id:"s",schedule_type:"FIRST_YEAR",days:[{working_day_id:"m",day_name:"Monday",sequence_number:1,entries:[{...common,entry_id:"e1",course_code:"CSL1",course_name:"Programming Lab",faculty_code:"VCE001",laboratory_code:"LAB-1",batch_name:"A1"},{...common,entry_id:"e2",course_code:"CSL2",course_name:"Graphics Lab",faculty_code:"VCE002",laboratory_code:"LAB-2",batch_name:"A2"}]}]};render(<SectionTimetableGrid grid={grid}/>);expect(screen.getByText(/Synchronized rotation block/)).toHaveTextContent("2 parallel groups");expect(screen.getByText("CSL1").closest("td")).toBe(screen.getByText("CSL2").closest("td"));expect(screen.getByText("A1")).toBeInTheDocument();expect(screen.getByText("A2")).toBeInTheDocument()});
  it("renders a readable combined-teaching label for screen and print views",()=>{const grid:TimetableGrid={version_id:"v",view_type:"faculty",resource_id:"faculty",schedule_type:"HIGHER_YEAR",days:[{working_day_id:"m",day_name:"Monday",sequence_number:1,entries:[{entry_id:"e1",combined_teaching_event_id:"event-1",combined_teaching_group_code:"DS-CSE-AB",combined_section_codes:["CSE-A","CSE-B"],working_day_id:"m",day_name:"Monday",period_number:2,period_numbers:[2],schedule_type:"HIGHER_YEAR",start_time:"10:10:00",end_time:"11:00:00",course_code:"CS301",course_name:"Data Structures",course_type:"THEORY",section_code:"CSE-A",faculty_code:"VCE042",faculty_name:"Dr. X",classroom_room_number:"1101",session_length:1,entry_status:"GENERATED",is_manual:false,is_locked:false}]}]};render(<SectionTimetableGrid grid={grid}/>);expect(screen.getByText("Combined: CSE-A + CSE-B")).toBeInTheDocument();expect(screen.getByText("DS-CSE-AB")).toBeInTheDocument();expect(screen.getAllByText("CS301")).toHaveLength(1)});
});
