"use client";

import clsx from "clsx";
import { useEffect, useId, useRef, type ReactNode } from "react";
import { X } from "lucide-react";

export function StatusBadge({ value }: { value: string }) { const tone = value.includes("FAIL") || value.includes("CONFLICT") ? "bg-red-100 text-red-700" : value.includes("WARN") || value.includes("REVIEW") ? "bg-amber-100 text-amber-800" : value === "ACTIVE" || value.includes("PASS") || value.includes("PUBLISH") || value.includes("OPTIMAL") ? "bg-emerald-100 text-emerald-700" : value.includes("LOCK") ? "bg-violet-100 text-violet-700" : "bg-slate-100 text-slate-700"; return <span className={clsx("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", tone)}>{value.replaceAll("_", " ")}</span> }
export function Card({ title, children, className }: { title?: string; children: ReactNode; className?: string }) { return <section className={clsx("panel p-5", className)}>{title && <h2 className="mb-4 text-base font-semibold">{title}</h2>}{children}</section> }
export function LoadingState({ label = "Loading" }: { label?: string }) { return <div role="status" className="space-y-3 p-2"><span className="sr-only">{label}</span>{[1,2,3].map((x) => <div key={x} className="h-12 animate-pulse rounded-lg bg-slate-200" />)}</div> }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p>{message}</p>{retry && <button className="mt-3 font-semibold underline" onClick={retry}>Try again</button>}</div> }
export function EmptyState({ title, detail }: { title: string; detail?: string }) { return <div className="rounded-lg border border-dashed border-slate-300 p-8 text-center"><p className="font-medium text-slate-700">{title}</p>{detail && <p className="mt-1 text-sm text-slate-500">{detail}</p>}</div> }
export function PageHeader({ title, description, actions }: { title: string; description?: string; actions?: ReactNode }) { return <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-slate-500">{description}</p>}</div>{actions}</div> }
export function Modal({ title, children, onClose, footer, wide = false }: { title: string; children: ReactNode; onClose(): void; footer?: ReactNode; wide?: boolean }) { const titleId = useId(); const dialog = useRef<HTMLElement>(null); const closeRef = useRef(onClose); closeRef.current = onClose; useEffect(() => { const previous = document.activeElement as HTMLElement | null; const handleKey = (event: KeyboardEvent) => { if (event.key === "Escape") closeRef.current(); if (event.key === "Tab" && dialog.current) { const controls = Array.from(dialog.current.querySelectorAll<HTMLElement>('button:not([disabled]), a[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])')); if (!controls.length) return; const first = controls[0]; const last = controls.at(-1)!; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", handleKey); return () => { document.removeEventListener("keydown", handleKey); previous?.focus(); }; }, []); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section ref={dialog} role="dialog" aria-modal="true" aria-labelledby={titleId} className={`max-h-[90vh] w-full overflow-y-auto rounded-2xl bg-white shadow-2xl dark:bg-slate-900 ${wide ? "max-w-5xl" : "max-w-xl"}`}><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4 dark:border-slate-700 dark:bg-slate-900"><h2 id={titleId} className="font-semibold">{title}</h2><button type="button" autoFocus aria-label="Close dialog" className="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800" onClick={onClose}><X className="h-4 w-4" /></button></header><div className="p-5">{children}</div>{footer && <footer className="sticky bottom-0 flex justify-end gap-2 border-t bg-white px-5 py-4 dark:border-slate-700 dark:bg-slate-900">{footer}</footer>}</section></div> }
