"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Card, EmptyState, ErrorState, LoadingState, Modal, StatusBadge } from "@/components/ui";
import { masterApi, timetableApi, versionOperationsApi } from "@/lib/api";
import { apiErrorMessage } from "@/lib/api-client";
import { queryKeys } from "@/lib/query-keys";
import type { SolverRun, Timetable, TimetableVersion } from "@/lib/types";
import { useAuth } from "@/providers/auth-provider";
import { useToast } from "@/providers/toast-provider";

const weights = ["theory_distribution_across_days", "same_course_same_day_excess", "same_course_adjacent_periods", "section_idle_gap", "faculty_idle_gap", "faculty_preferred_slot_violation", "faculty_avoid_slot_violation", "first_period_fairness", "last_period_fairness", "faculty_daily_load_imbalance", "section_daily_load_imbalance", "room_change", "laboratory_first_period_preference", "laboratory_last_period_penalty", "laboratory_day_spread"];
type WorkflowAction = { label: string; endpoint: string; roles: string[]; requiresReason?: boolean; disabledReason?: string };
const workflowActions: Record<string, WorkflowAction[]> = {
  DRAFT: [{ label: "Submit for review", endpoint: "submit-review", roles: ["Administrator", "Timetable Coordinator"], disabledReason: "Run the solver successfully before submitting for review." }],
  GENERATED: [{ label: "Submit for review", endpoint: "submit-review", roles: ["Administrator", "Timetable Coordinator"] }],
  UNDER_REVIEW: [{ label: "Approve", endpoint: "approve", roles: ["Administrator", "Dean", "Principal"] }, { label: "Return to draft", endpoint: "return-to-draft", roles: ["Administrator", "Timetable Coordinator"], requiresReason: true }],
  APPROVED: [{ label: "Publish", endpoint: "publish", roles: ["Administrator", "Principal"] }, { label: "Return to draft", endpoint: "return-to-draft", roles: ["Administrator", "Timetable Coordinator"], requiresReason: true }],
  PUBLISHED: [{ label: "Archive", endpoint: "archive", roles: ["Administrator"] }],
};

export function VersionActions({ version, timetable }: { version: TimetableVersion; timetable: Timetable }) {
  const { hasRole } = useAuth();
  const client = useQueryClient();
  const { notify } = useToast();
  const isAdministrator = hasRole("Administrator", "System Administrator");
  const canBuild = isAdministrator || hasRole("Timetable Coordinator");
  const canSolve = canBuild;
  const canCopy = canBuild;
  const canViewSolverInput = canBuild || hasRole("HOD");
  const buildDisabledReason = !version.is_active ? "Inactive versions cannot build solver input." : version.is_locked ? "Locked versions cannot rebuild solver input." : timetable.status === "ARCHIVED" ? "Archived timetables are read-only." : undefined;
  const solveDisabledReason = !version.is_active ? "Inactive versions cannot run the solver." : version.is_locked ? "Locked versions cannot run the solver." : ["APPROVED", "PUBLISHED", "ARCHIVED"].includes(timetable.status) ? `${timetable.status.replaceAll("_", " ")} timetables are immutable.` : version.solver_status === "RUNNING" ? "A solver run is already in progress." : undefined;
  const copyDisabledReason = ["PUBLISHED", "ARCHIVED"].includes(timetable.status) ? `${timetable.status.replaceAll("_", " ")} timetables cannot be copied.` : undefined;
  const permittedWorkflow = (workflowActions[timetable.status] ?? []).filter((action) => action.roles.some((role) => role === "Administrator" ? isAdministrator : hasRole(role)));
  const [solveOpen, setSolveOpen] = useState(false);
  const [copyOpen, setCopyOpen] = useState(false);
  const workflow = useMutation({ mutationFn: async (action: WorkflowAction) => { if (!window.confirm(`${action.label}?`)) throw new Error("Action cancelled"); let body: Record<string, unknown> = {}; if (action.requiresReason) { const reason = window.prompt("Reason for returning this timetable to draft"); if (!reason?.trim()) throw new Error("Action cancelled"); body = { reason: reason.trim() }; } return timetableApi.transition(timetable.id, action.endpoint, body); }, onSuccess: (_, action) => { notify(`${action.label} completed`); for (const key of [queryKeys.timetable(timetable.id), queryKeys.versions(timetable.id), queryKeys.version(version.id), queryKeys.history(timetable.id), queryKeys.dashboard]) void client.invalidateQueries({ queryKey: key }); }, onError: (error) => { if (error instanceof Error && error.message === "Action cancelled") return; notify(apiErrorMessage(error), "error"); } });
  return <div className="mb-5 space-y-4"><Card title="Solver and workflow actions"><div className="mb-3 flex flex-wrap items-center gap-2"><StatusBadge value={version.solver_status} />{version.is_locked && <StatusBadge value="LOCKED" />}{!version.is_active && <StatusBadge value="INACTIVE" />}</div><div className="flex flex-wrap gap-2">{canBuild && <BuildInputButton versionId={version.id} disabledReason={buildDisabledReason} />}{canSolve && <button className="button-primary" title={solveDisabledReason} disabled={Boolean(solveDisabledReason)} onClick={() => setSolveOpen(true)}>Run solver</button>}{canCopy && <button className="button-secondary" title={copyDisabledReason} disabled={Boolean(copyDisabledReason)} onClick={() => setCopyOpen(true)}>Copy version</button>}{permittedWorkflow.map((action) => <button key={action.endpoint} className="button-secondary" title={action.disabledReason} disabled={workflow.isPending || Boolean(action.disabledReason)} onClick={() => workflow.mutate(action)}>{action.label}</button>)}</div>{(buildDisabledReason || solveDisabledReason || copyDisabledReason || permittedWorkflow.some((action) => action.disabledReason)) && <ul className="mt-3 space-y-1 text-xs text-slate-500">{Array.from(new Set([buildDisabledReason, solveDisabledReason, copyDisabledReason, ...permittedWorkflow.map((action) => action.disabledReason)].filter((reason): reason is string => Boolean(reason)))).map((reason) => <li key={reason}>• {reason}</li>)}</ul>}{!canBuild && !canCopy && !permittedWorkflow.length && <p className="mt-3 text-sm text-slate-500">Your role has read-only access to this version.</p>}</Card>{canViewSolverInput && <SolverInputPanel versionId={version.id} solverStatus={version.solver_status} />}{solveOpen && <SolveDialog version={version} onClose={() => setSolveOpen(false)} />}{copyOpen && <CopyDialog version={version} timetableId={timetable.id} onClose={() => setCopyOpen(false)} />}</div>;
}

function BuildInputButton({ versionId, disabledReason }: { versionId: string; disabledReason?: string }) {
  const client = useQueryClient(); const { notify } = useToast();
  const snapshot = useQuery({ queryKey: queryKeys.solverInput(versionId), queryFn: () => versionOperationsApi.solverInput(versionId), retry: false });
  const mutation = useMutation({ mutationFn: () => versionOperationsApi.buildInput(versionId), onSuccess: (snapshot) => { notify(`Solver input ready: ${snapshot.input_hash.slice(0, 12)}…`); void client.invalidateQueries({ queryKey: queryKeys.version(versionId) }); void client.invalidateQueries({ queryKey: queryKeys.solverInput(versionId) }); }, onError: (error) => notify(apiErrorMessage(error), "error") });
  const label = snapshot.data ? "Rebuild solver input" : "Build solver input";
  return <button className="button-primary" title={disabledReason} disabled={mutation.isPending || Boolean(disabledReason)} onClick={() => { if (window.confirm(`${label}? Existing identical snapshots will be reused.`)) mutation.mutate(); }}>{mutation.isPending ? "Building…" : label}</button>;
}

export function SolverInputPanel({ versionId, solverStatus }: { versionId: string; solverStatus?: string }) {
  const { hasRole } = useAuth();
  const query = useQuery({ queryKey: queryKeys.solverInput(versionId), queryFn: () => versionOperationsApi.solverInput(versionId), retry: false });
  if (query.isLoading) return <Card title="Solver input"><LoadingState /></Card>;
  if (query.isError) return <Card title="Solver input"><EmptyState title="No solver input snapshot" detail={apiErrorMessage(query.error)} /></Card>;
  const snapshot = query.data!; const data = snapshot.snapshot_json;
  const counts = [["Sections", count(data.sections)], ["Course offerings", count(data.course_offerings)], ["Faculty", count(data.faculty)], ["Classrooms", count(data.classrooms)], ["Laboratories", count(data.laboratories)], ["Locked entries", count(data.locked_entries)]];
  return <Card title="Solver input"><div className="mb-4 flex items-center gap-2"><StatusBadge value={solverStatus === "STALE" ? "STALE" : "READY"} /><span className="text-xs text-slate-500">Use Rebuild solver input after timetable data or manual entries change.</span></div><div className="grid gap-3 md:grid-cols-2"><Metric label="Input hash" value={snapshot.input_hash} /><Metric label="Created" value={new Date(snapshot.created_at).toLocaleString()} /></div><div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{counts.map(([label, value]) => <Metric key={String(label)} label={String(label)} value={String(value)} />)}</div>{hasRole("Administrator", "System Administrator") && <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold text-brand-700">Raw canonical snapshot JSON</summary><pre className="mt-3 max-h-96 overflow-auto rounded-lg bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(data, null, 2)}</pre></details>}</Card>;
}

export function SolveDialog({ version, onClose }: { version: TimetableVersion; onClose(): void }) {
  const client = useQueryClient(); const { notify } = useToast(); const [profile, setProfile] = useState("BALANCED"); const [timeLimit, setTimeLimit] = useState(60); const [seed, setSeed] = useState(1); const [overrides, setOverrides] = useState<Record<string, string>>({}); const [result, setResult] = useState<SolverRun | null>(null);
  const mutation = useMutation({ mutationFn: () => { const parsed: Record<string, number> = {}; for (const [name, raw] of Object.entries(overrides)) { if (!raw) continue; const value = Number(raw); if (!Number.isInteger(value) || value < 0) throw new Error(`${name.replaceAll("_", " ")} must be a nonnegative integer`); parsed[name] = value; } if (!Number.isInteger(timeLimit) || timeLimit < 1 || timeLimit > 300) throw new Error("Time limit must be between 1 and 300 seconds"); if (!Number.isInteger(seed) || seed < 0) throw new Error("Random seed must be a nonnegative integer"); return versionOperationsApi.solve(version.id, { optimization_profile: profile, time_limit_seconds: timeLimit, random_seed: seed, weight_overrides: parsed }); }, onSuccess: (run) => { setResult(run); notify(`Solver finished with ${run.status}`); for (const key of [queryKeys.version(version.id), queryKeys.entries(version.id), queryKeys.sectionGrids(version.id), queryKeys.timetableViews(version.id), queryKeys.versionSolverRuns(version.id), queryKeys.quality(run.id), queryKeys.conflicts(version.id), queryKeys.dashboard]) void client.invalidateQueries({ queryKey: key }); }, onError: (error) => notify(apiErrorMessage(error), "error") });
  const error = mutation.isError ? apiErrorMessage(mutation.error) : "";
  return <Modal title="Run timetable solver" onClose={onClose} wide footer={<><button className="button-secondary" onClick={onClose}>Close</button><button className="button-primary" disabled={mutation.isPending} onClick={() => { if (window.confirm("Run the solver with this configuration?")) mutation.mutate(); }}>{mutation.isPending ? "Solving…" : "Run solver"}</button></>}><div className="grid gap-4 sm:grid-cols-3"><label><span className="label">Optimization profile</span><select className="field" value={profile} onChange={(event) => setProfile(event.target.value)}>{["FAST", "BALANCED", "QUALITY"].map((item) => <option key={item}>{item}</option>)}</select></label><label><span className="label">Time limit seconds</span><input className="field" type="number" min={1} max={300} value={timeLimit} onChange={(event) => setTimeLimit(Number(event.target.value))} /></label><label><span className="label">Random seed</span><input className="field" type="number" min={0} value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label></div><details className="mt-5"><summary className="cursor-pointer font-semibold">Optional weight overrides</summary><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{weights.map((name) => <label key={name}><span className="label text-xs">{name.replaceAll("_", " ")}</span><input aria-label={name} className="field" type="number" min={0} step={1} value={overrides[name] ?? ""} onChange={(event) => setOverrides({ ...overrides, [name]: event.target.value })} /></label>)}</div></details>{error && <div className="mt-4"><ErrorState message={error} />{error.toLowerCase().includes("stale") && <p className="mt-2 text-sm font-medium text-amber-700">Rebuild the solver input before solving again.</p>}</div>}{result && <div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric label="Status" value={result.status} /><Metric label="Runtime" value={result.runtime_seconds == null ? "—" : `${result.runtime_seconds.toFixed(2)}s`} /><Metric label="Entries" value={String(result.generated_entry_count)} /><Metric label="Objective / bound" value={`${result.objective_value ?? "—"} / ${result.best_bound ?? "—"}`} /><Metric label="Quality" value={String(readQuality(result) ?? "—")} /><Metric label="Penalty" value={String(readPenalty(result) ?? "—")} /></div>}</Modal>;
}

function CopyDialog({ version, timetableId, onClose }: { version: TimetableVersion; timetableId: string; onClose(): void }) {
  const [name, setName] = useState(`Copy of version ${version.version_number}`); const client = useQueryClient(); const router = useRouter(); const { notify } = useToast();
  const mutation = useMutation({ mutationFn: () => versionOperationsApi.copy(version.id, { version_name: name.trim(), source_type: "MANUAL_COPY" }), onSuccess: (created) => { notify("Version copied. Rebuild solver input before solving.", "info"); void client.invalidateQueries({ queryKey: queryKeys.versions(timetableId) }); void client.invalidateQueries({ queryKey: queryKeys.timetable(timetableId) }); router.push(`/timetable-versions/${created.id}`); }, onError: (error) => notify(apiErrorMessage(error), "error") });
  return <Modal title="Copy timetable version" onClose={onClose} footer={<><button className="button-secondary" onClick={onClose}>Cancel</button><button className="button-primary" disabled={!name.trim() || mutation.isPending} onClick={() => { if (window.confirm("Create this manual review copy?")) mutation.mutate(); }}>Copy version</button></>}><label><span className="label">Version name</span><input className="field" value={name} onChange={(event) => setName(event.target.value)} /></label><p className="mt-3 text-sm text-slate-600">Source type: MANUAL_COPY. Solver input must be rebuilt for the new version.</p></Modal>;
}

export function FreeResourcesPanel({ versionId, workingDays = [] }: { versionId: string; workingDays?: { id: string; name: string; actualDate?: string | null }[] }) {
  const [dayKey, setDayKey] = useState(""); const [period, setPeriod] = useState(1); const [lookup, setLookup] = useState<{ day: string; actualDate?: string; period: number } | null>(null);
  const { hasRole } = useAuth();
  const canListWorkingDays = hasRole("Administrator", "System Administrator", "Timetable Coordinator", "HOD");
  const days = useQuery({ queryKey: queryKeys.workingDays, queryFn: masterApi.workingDays, enabled: canListWorkingDays && !workingDays.length });
  const dayOptions = workingDays.length ? workingDays : days.data?.items.map((item) => ({ id: item.id, name: item.day_name, actualDate: null })) ?? [];
  const selectedDay = dayOptions.find((item) => (item.actualDate ?? item.id) === dayKey);
  const findFree = (kind: "faculty" | "classrooms" | "laboratories") => lookup!.actualDate ? versionOperationsApi.free(versionId, kind, lookup!.day, lookup!.period, lookup!.actualDate) : versionOperationsApi.free(versionId, kind, lookup!.day, lookup!.period);
  const faculty = useQuery({ queryKey: queryKeys.freeResources(versionId, "faculty", lookup), queryFn: () => findFree("faculty"), enabled: Boolean(lookup) });
  const classrooms = useQuery({ queryKey: queryKeys.freeResources(versionId, "classrooms", lookup), queryFn: () => findFree("classrooms"), enabled: Boolean(lookup) });
  const laboratories = useQuery({ queryKey: queryKeys.freeResources(versionId, "laboratories", lookup), queryFn: () => findFree("laboratories"), enabled: Boolean(lookup) });
  return <Card title="Free resources"><div className="flex flex-wrap items-end gap-3"><label className="min-w-64"><span className="label">{dayOptions.some((item) => item.actualDate) ? "Working date" : "Working day"}</span><select className="field" value={dayKey} disabled={!dayOptions.length || days.isLoading} onChange={(event) => setDayKey(event.target.value)}><option value="">{days.isLoading ? "Loading working days…" : dayOptions.length ? "Select day" : "No working days available"}</option>{dayOptions.map((item) => <option key={item.actualDate ?? item.id} value={item.actualDate ?? item.id}>{item.name}</option>)}</select></label><label><span className="label">Period</span><select className="field" value={period} onChange={(event) => setPeriod(Number(event.target.value))}>{[1, 2, 3, 4, 5, 6, 7].map((item) => <option key={item}>{item}</option>)}</select></label><button className="button-secondary" disabled={!selectedDay || faculty.isFetching || classrooms.isFetching || laboratories.isFetching} onClick={() => selectedDay && setLookup({ day: selectedDay.id, actualDate: selectedDay.actualDate ?? undefined, period })}>{faculty.isFetching || classrooms.isFetching || laboratories.isFetching ? "Checking…" : "Find free resources"}</button></div>{days.isError && canListWorkingDays && <div className="mt-3"><ErrorState message="Working days could not be loaded for this lookup." /></div>}{lookup && <div className="mt-5 grid gap-4 lg:grid-cols-3"><ResourceList title="Faculty" query={faculty} /><ResourceList title="Classrooms" query={classrooms} /><ResourceList title="Laboratories" query={laboratories} /></div>}</Card>;
}

function ResourceList({ title, query }: { title: string; query: { isLoading: boolean; isError: boolean; error: unknown; data?: { items: Record<string, string | number | null>[] } } }) { return <div className="rounded-xl border p-4"><h3 className="font-semibold">{title}</h3>{query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={apiErrorMessage(query.error)} /> : !query.data?.items.length ? <p className="mt-3 text-sm text-slate-500">None available</p> : <ul className="mt-3 space-y-2 text-sm">{query.data.items.map((item, index) => <li key={String(item.id ?? index)} className="rounded bg-slate-50 p-2">{String(item.faculty_code ?? item.room_number ?? item.laboratory_code ?? "Resource metadata unavailable")}{(item.full_name ?? item.room_name ?? item.laboratory_name) ? ` · ${String(item.full_name ?? item.room_name ?? item.laboratory_name)}` : ""}{item.concurrent_usage_mode === "CAPACITY_SHARED" && <span className="mt-1 block text-xs font-medium text-violet-700">Capacity {String(item.capacity)} · Occupied {String(item.occupied)} · Available {String(item.available)}</span>}</li>)}</ul>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-all text-sm font-semibold">{value}</p></div>; }
function count(value: unknown) { return Array.isArray(value) ? value.length : 0; }
function readQuality(run: SolverRun) { const stats = run.statistics_json ?? {}; const metrics = typeof stats.quality_metrics === "object" && stats.quality_metrics ? stats.quality_metrics as Record<string, unknown> : {}; return typeof metrics.quality_score === "number" ? metrics.quality_score : typeof stats.solution_quality_score === "number" ? stats.solution_quality_score : undefined; }
function readPenalty(run: SolverRun) { const value = run.statistics_json?.total_penalty; return typeof value === "number" ? value : undefined; }
