"""Create student batches and laboratory rotation configuration.
Revision ID: 0014
Revises: 0013
"""
from alembic import op
import sqlalchemy as sa
revision="0014";down_revision="0013";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("student_batches",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("section_id",sa.Uuid(),nullable=False),sa.Column("batch_name",sa.String(20),nullable=False),sa.Column("sequence_number",sa.Integer(),nullable=False),sa.Column("roll_number_start",sa.Integer(),nullable=False),sa.Column("roll_number_end",sa.Integer(),nullable=False),sa.Column("student_count",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.ForeignKeyConstraint(["section_id"],["sections.id"]),sa.UniqueConstraint("section_id","batch_name"),sa.UniqueConstraint("section_id","sequence_number"),sa.CheckConstraint("roll_number_end >= roll_number_start AND student_count = roll_number_end - roll_number_start + 1"))
 op.create_table("laboratory_batch_configurations",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("course_offering_id",sa.Uuid(),nullable=False),sa.Column("section_id",sa.Uuid(),nullable=False),sa.Column("number_of_batches",sa.Integer(),nullable=False),sa.Column("is_rotation_enabled",sa.Boolean(),nullable=False),sa.Column("is_weekly_rotation",sa.Boolean(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.ForeignKeyConstraint(["course_offering_id"],["course_offerings.id"]),sa.ForeignKeyConstraint(["section_id"],["sections.id"]),sa.UniqueConstraint("course_offering_id"),sa.CheckConstraint("number_of_batches IN (1,2,3)"))
 op.create_table("laboratory_rotation_groups",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("laboratory_batch_configuration_id",sa.Uuid(),nullable=False),sa.Column("rotation_code",sa.String(100),nullable=False),sa.Column("rotation_type",sa.String(20),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.ForeignKeyConstraint(["laboratory_batch_configuration_id"],["laboratory_batch_configurations.id"]),sa.CheckConstraint("rotation_type IN ('FIXED','CYCLIC')"))
 op.create_table("laboratory_rotation_assignments",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("rotation_group_id",sa.Uuid(),nullable=False),sa.Column("batch_id",sa.Uuid(),nullable=False),sa.Column("course_offering_id",sa.Uuid(),nullable=False),sa.Column("rotation_position",sa.Integer(),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()")),sa.ForeignKeyConstraint(["rotation_group_id"],["laboratory_rotation_groups.id"]),sa.ForeignKeyConstraint(["batch_id"],["student_batches.id"]),sa.ForeignKeyConstraint(["course_offering_id"],["course_offerings.id"]),sa.UniqueConstraint("rotation_group_id","batch_id","course_offering_id"),sa.UniqueConstraint("rotation_group_id","rotation_position"))
def downgrade():op.drop_table("laboratory_rotation_assignments");op.drop_table("laboratory_rotation_groups");op.drop_table("laboratory_batch_configurations");op.drop_table("student_batches")
