import { afterEach,describe,expect,it } from "vitest";
import type { AxiosAdapter,AxiosResponse } from "axios";
import { api } from "@/lib/api-client";
import { authApi,entryOperationsApi,timetableApi,versionOperationsApi } from "@/lib/api";
import { tokenStore } from "@/lib/token-store";

const originalAdapter=api.defaults.adapter;
afterEach(()=>{api.defaults.adapter=originalAdapter});
describe("typed API client",()=>{
 it("adds the bearer token automatically",async()=>{tokenStore.set({access_token:"access-123",refresh_token:"refresh-123",token_type:"bearer"});let authorization:unknown;api.defaults.adapter=(async config=>{authorization=config.headers?.Authorization;return response(config,{ok:true})}) as AxiosAdapter;await api.get("/check");expect(authorization).toBe("Bearer access-123")});
 it("supports the login to timetable list to version request flow",async()=>{const calls:string[]=[];api.defaults.adapter=(async config=>{calls.push(String(config.url));if(config.url==="/auth/login")return response(config,{access_token:"new-access",refresh_token:"new-refresh",token_type:"bearer"});if(config.url==="/timetables")return response(config,{items:[{id:"tt-1"}],total:1,page:1,page_size:20,pages:1});return response(config,{id:"version-1",timetable_id:"tt-1",version_number:1})}) as AxiosAdapter;tokenStore.set(await authApi.login("admin@vce.ac.in","Password123"));const list=await timetableApi.list({page:1});const version=await timetableApi.version("version-1");expect(list.total).toBe(1);expect(version.id).toBe("version-1");expect(calls).toEqual(["/auth/login","/timetables","/timetable-versions/version-1"])});
 it("supports the Phase 2 coordinator workflow",async()=>{const calls:string[]=[];api.defaults.adapter=(async config=>{calls.push(String(config.url));if(config.url==="/auth/login")return response(config,{access_token:"access",refresh_token:"refresh",token_type:"bearer"});if(config.url?.endsWith("/copy"))return response(config,{id:"version-copy",timetable_id:"tt-1",version_number:2});if(config.url?.endsWith("/build-solver-input"))return response(config,{id:"snapshot",input_hash:"hash",snapshot_json:{}});if(config.url?.endsWith("/solve"))return response(config,{id:"solver",status:"OPTIMAL"});if(config.url?.endsWith("/move")||config.url?.endsWith("/lock"))return response(config,{id:"entry-1"});return response(config,{id:"tt-1",status:"UNDER_REVIEW"})}) as AxiosAdapter;tokenStore.set(await authApi.login("coordinator@vce.ac.in","Password123"));await timetableApi.get("tt-1");const copy=await versionOperationsApi.copy("version-1",{version_name:"Review copy",source_type:"MANUAL_COPY"});await versionOperationsApi.buildInput(copy.id);await versionOperationsApi.solve(copy.id,{optimization_profile:"BALANCED",time_limit_seconds:60,random_seed:1,weight_overrides:{}});await entryOperationsApi.move("entry-1",{working_day_id:"day",period_number:2,lock_after_move:false});await entryOperationsApi.lock("entry-1");await timetableApi.transition("tt-1","submit-review");expect(calls).toEqual(["/auth/login","/timetables/tt-1","/timetable-versions/version-1/copy","/timetable-versions/version-copy/build-solver-input","/timetable-versions/version-copy/solve","/timetable-entries/entry-1/move","/timetable-entries/entry-1/lock","/timetables/tt-1/submit-review"])});
});
function response(config:Parameters<AxiosAdapter>[0],data:unknown):AxiosResponse{return{data,status:200,statusText:"OK",headers:{},config}}
