export const queryKeys = {
  dashboard: ["dashboard"] as const,
  users: ["users"] as const,
  user: (id: string) => ["users", id] as const,
  roles: ["roles"] as const,
  academicTerms: ["academic-terms"] as const,
  departments: (context = "default") => ["departments", context] as const,
  programs: (context = "default") => ["programs", context] as const,
  sections: (context = "default", academicTermId = "") => ["sections", context, academicTermId] as const,
  workingDays: ["working-days"] as const,
  classrooms: (context = "default") => ["classrooms", context] as const,
  laboratories: (context = "default") => ["laboratories", context] as const,
  timetable: (id: string) => ["timetable", id] as const,
  timetables: (filters: object = {}) => ["timetables", filters] as const,
  versions: (id: string) => ["versions", id] as const,
  version: (id: string) => ["version", id] as const,
  entries: (id: string) => ["version-entries", id] as const,
  sectionGrid: (id: string, sectionId: string) => ["section-grid", id, sectionId] as const,
  sectionGrids: (id: string) => ["section-grid", id] as const,
  timetableView: (id: string, viewType: string, resourceId: string) => ["timetable-view", id, viewType, resourceId] as const,
  timetableViews: (id: string) => ["timetable-view", id] as const,
  solverInput: (id: string) => ["solver-input", id] as const,
  solverRuns: (filters: object = {}) => ["solver-runs", filters] as const,
  solverRun: (id: string) => ["solver-run", id] as const,
  versionSolverRuns: (id: string) => ["solver-runs", id] as const,
  quality: (id: string) => ["quality", id] as const,
  conflicts: (id: string) => ["conflicts", id] as const,
  audit: (id: string) => ["entry-audit", id] as const,
  history: (id: string) => ["status-history", id] as const,
  validationRuns: (filters: object = {}) => ["validation-runs", filters] as const,
  validationRunsRoot: ["validation-runs"] as const,
  validationRun: (id: string) => ["validation-run", id] as const,
  validationIssues: (id: string, filters: object = {}) => ["validation-issues", id, filters] as const,
  comparisonVersions: (timetableId: string) => ["comparison-versions", timetableId] as const,
  comparison: (versionId: string, otherVersionId: string) => ["comparison", versionId, otherVersionId] as const,
  freeResources: (versionId: string, resource: string, slot: object | null) => ["free-resources", versionId, resource, slot] as const,
  globalSearch: (term: string) => ["global-search", term] as const,
  report: (type: string, filters: object) => ["report", type, filters] as const,
};
