export interface Permission { id: string; resource: string; action: string; description?: string | null }
export interface Role { id: string; name: string; description?: string | null; permissions: Permission[] }
export interface User { id: string; email: string; full_name: string; is_active: boolean; roles: Role[] }
export interface TokenPair { access_token: string; refresh_token: string; token_type: string }
export interface Page<T> { items: T[]; total: number; page: number; page_size: number; pages: number }
export interface Timetable { id: string; academic_term_id: string; scope_type: string; department_id?: string | null; program_id?: string | null; section_id?: string | null; name: string; status: string; active_version_id?: string | null; created_by: string; created_at: string; updated_at: string }
export interface TimetableVersion { id: string; timetable_id: string; version_number: number; version_name?: string | null; source_type: string; validation_run_id: string; solver_status: string; is_active: boolean; is_locked: boolean; created_by: string; created_at: string; updated_at: string }
export interface TimetableEntry { id: string; timetable_version_id: string; course_offering_id: string; section_id: string; faculty_id?: string | null; classroom_id?: string | null; laboratory_id?: string | null; student_batch_id?: string | null; laboratory_rotation_block_id?: string | null; laboratory_rotation_assignment_id?: string | null; combined_teaching_event_id?: string | null; working_day_id: string; period_number: number; session_length: number; entry_type: string; is_manual: boolean; is_locked: boolean }
export interface SolverRun { id: string; timetable_version_id: string; solver_input_snapshot_id: string; status: string; started_at: string; completed_at?: string | null; runtime_seconds?: number | null; objective_value?: number | null; best_bound?: number | null; generated_entry_count: number; message?: string | null; statistics_json?: Record<string, unknown> | null; created_by: string; created_at: string }
export interface QualityMetrics { total_penalty: number; quality_score: number; optimization_profile: string; objective_breakdown: Record<string, number>; faculty_daily_loads: Record<string, Record<string, number>>; faculty_first_last_counts: Record<string, { first: number; last: number }>; faculty_idle_gap_counts: Record<string, number>; section_daily_loads: Record<string, Record<string, number>>; section_idle_gap_counts: Record<string, number>; course_day_distribution: Record<string, Record<string, number>>; laboratory_day_distribution: Record<string, Record<string, number>>; room_change_counts: Record<string, number> }
export interface GridEntry { entry_id: string; laboratory_rotation_block_id?: string | null; combined_teaching_event_id?: string | null; combined_teaching_group_code?: string | null; combined_section_codes?: string[]; working_day_id: string; day_name: string; period_number: number; period_numbers: number[]; schedule_type: string; start_time: string; end_time: string; course_code: string; course_name: string; course_type: string; section_code: string; faculty_code?: string | null; faculty_name?: string | null; classroom_room_number?: string | null; laboratory_code?: string | null; laboratory_name?: string | null; batch_name?: string | null; capacity_demand?: number | null; resource_capacity?: number | null; occupied_capacity?: number | null; available_capacity?: number | null; concurrent_usage_mode?: "EXCLUSIVE" | "CAPACITY_SHARED" | null; session_length: number; entry_status: string; is_manual: boolean; is_locked: boolean }
export interface GridDay { working_day_id: string; day_name: string; sequence_number: number; entries: GridEntry[] }
export interface TimetableGrid { version_id: string; view_type: string; resource_id: string; schedule_type: string; days: GridDay[] }
export interface Conflict { conflict_type: string; entry_ids: string[]; message: string; affected_entity?: string; day_name?: string; period_number?: number }
export interface ConflictReport { version_id: string; conflicts: Conflict[]; summary: Record<string, number> }
export interface StatusHistory { id: string; from_status: string; to_status: string; reason?: string | null; performed_by: string; created_at: string }
export interface AcademicTerm { id: string; academic_year: string; term_name: string; year_number: number; semester_number: number; is_active: boolean; is_current: boolean }
export interface Department { id: string; department_code: string; department_name: string; short_name: string; is_active: boolean }
export interface Program { id: string; department_id: string; program_code: string; program_name: string; is_active: boolean }
export interface Section { id: string; program_id: string; academic_term_id: string; section_name: string; section_code: string; student_strength: number; is_active: boolean }
export interface WorkingDay { id: string; day_name: string; sequence_number: number; is_working_day: boolean; is_active: boolean }
export interface Classroom { id: string; room_number: string; room_name?: string | null; capacity?: number | null; is_active: boolean }
export interface Laboratory { id: string; laboratory_code: string; laboratory_name: string; room_number: string; owning_department_id?: string; capacity?: number | null; concurrent_usage_mode?: "EXCLUSIVE" | "CAPACITY_SHARED"; is_shareable_across_departments?: boolean; is_available_all_periods?: boolean; availability_mode?: "ALL_PERIODS" | "EXCEPT_BLOCKED" | "ONLY_SELECTED"; is_active: boolean }
export interface Faculty { id: string; faculty_code: string; full_name: string; department_id: string; designation: string; institutional_email: string; minimum_weekly_workload: number; maximum_weekly_workload: number; maximum_periods_per_day?: number | null; is_active: boolean }
export interface Course { id: string; course_code: string; course_name: string; offering_department_id: string; course_type: string; grouping_mode: "FULL_SECTION" | "GROUPED"; venue_requirement: "CLASSROOM_ONLY" | "LABORATORY_ONLY" | "CLASSROOM_OR_LABORATORY" | "NO_FIXED_VENUE"; weekly_periods: number; session_duration: number; sessions_per_week: number; default_group_count: number; eligible_laboratory_ids: string[]; default_laboratory_id?: string | null; is_active: boolean }
export interface StudentBatch { id: string; section_id: string; batch_name: string; sequence_number: number; student_count: number; is_active: boolean }
export interface WorkloadPreview { faculty_id: string; weekly_workload_hours: number }
export interface ValidationIssue { id: string; severity: string; issue_code: string; entity_type?: string | null; entity_id?: string | null; message: string; details?: Record<string, unknown> | null; created_at: string }
export interface ValidationRun { id: string; academic_term_id: string; scope_type: string; department_id?: string | null; program_id?: string | null; section_id?: string | null; status: string; total_checks: number; passed_checks: number; failed_checks: number; warning_checks: number; started_at: string; completed_at: string; created_by: string; created_at: string; issues?: ValidationIssue[] }
export interface SolverInputSnapshot { id: string; timetable_version_id: string; snapshot_json: Record<string, unknown>; input_hash: string; created_at: string }
export interface EntryAudit { id: string; timetable_entry_id: string; timetable_version_id: string; action_type: string; old_values_json?: Record<string, unknown> | null; new_values_json?: Record<string, unknown> | null; reason?: string | null; performed_by: string; created_at: string }
export interface VersionComparison { version_id: string; other_version_id: string; added_entries: Record<string, unknown>[]; removed_entries: Record<string, unknown>[]; moved_entries: { from: Record<string, unknown>; to: Record<string, unknown> }[]; faculty_changes: { from: Record<string, unknown>; to: Record<string, unknown> }[]; facility_changes: { from: Record<string, unknown>; to: Record<string, unknown> }[]; lock_state_changes: { from: Record<string, unknown>; to: Record<string, unknown> }[]; summary: Record<string, number> }
export interface FreeResourceResponse { version_id: string; working_day_id: string; period_number: number; items: Record<string, string | number | null>[] }
export interface ReportColumn { key: string; label: string; group: string; data_type: string; sortable: boolean; default_width: number; alignment: string }
export interface ReportFilter { key: string; label: string; control: string; options: string[] }
export interface ReportSort { key: string; direction: "asc" | "desc" }
export interface ReportDefinition { key: string; title: string; description: string; layout_type: string; columns: ReportColumn[]; default_columns: string[]; filters: ReportFilter[]; default_sort: ReportSort[]; supported_formats: ("xlsx" | "csv" | "docx" | "pdf")[] }
export interface ReportRequest { report_key: string; filters: Record<string, string | string[]>; selected_columns: string[]; sort_fields: ReportSort[]; page: number; page_size: number }
export interface ReportPreview { report_key: string; title: string; columns: ReportColumn[]; filters: Record<string, unknown>; filter_summary: string[]; sorting: ReportSort[]; rows: Record<string, unknown>[]; total: number; page: number; page_size: number; pages: number; configuration_signature: string }
